channels:
- conda-forge
dependencies:
- python=3.10
- pip
- pandas
- geopandas
- shapely
- utm
- numpy
- pendulum
# - branca
# - plotly
# - jenkspy
# - folium
- pip:
  - partridge
name: gtfs-functions